/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/clientes/{dni}": {
    /** Auto generated using Swagger Inspector */
    get: {
      parameters: {
        path: {
          dni: string;
        };
      };
      responses: {
        /** Auto generated using Swagger Inspector */
        200: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Cliente"];
          };
        };
        /** Auto generated using Swagger Inspector */
        400: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/vehiculosAsegurados/tipoVehiculo/{idVehiculoAsegurado}": {
    /** Auto generated using Swagger Inspector */
    get: {
      parameters: {
        path: {
          idVehiculoAsegurado: string;
        };
      };
      responses: {
        /** Auto generated using Swagger Inspector */
        200: {
          content: {
            "application/json; charset=utf-8": {
              tipoVehiculo?: string;
            };
          };
        };
        /** Auto generated using Swagger Inspector */
        400: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/coberturas/{marca}/{modelo}/{version}/{anio}": {
    /** Auto generated using Swagger Inspector */
    get: {
      parameters: {
        path: {
          marca: string;
          modelo: string;
          version: string;
          anio: string;
        };
      };
      responses: {
        /** Auto generated using Swagger Inspector */
        200: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Coberturas"];
          };
        };
        /** Auto generated using Swagger Inspector */
        400: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/polizas/vehiculoAsegurado/{patenteVehiculoAsegurado}": {
    /** Auto generated using Swagger Inspector */
    get: {
      parameters: {
        path: {
          patenteVehiculoAsegurado: string;
        };
      };
      responses: {
        /** Auto generated using Swagger Inspector */
        200: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Error"];
          };
        };
        /** Auto generated using Swagger Inspector */
        400: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/vehiculosAsegurados": {
    /** Auto generated using Swagger Inspector */
    post: {
      responses: {
        /** Auto generated using Swagger Inspector */
        200: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["VehiculoAsegurado"];
          };
        };
        /** Auto generated using Swagger Inspector */
        400: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Error"];
          };
        };
      };
      requestBody: {
        content: {
          "application/json": {
            color?: string;
            vehiculo?: {
              marca?: string;
              modelo?: string;
              version?: string;
              año?: string;
            };
            fotos?: string[];
            patente?: string;
          };
        };
      };
    };
  };
  "/api/polizas/cliente/{idCliente}": {
    /** Auto generated using Swagger Inspector */
    get: {
      parameters: {
        path: {
          idCliente: string;
        };
      };
      responses: {
        /** Auto generated using Swagger Inspector */
        200: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Polizas"];
          };
        };
        /** Auto generated using Swagger Inspector */
        400: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/polizas/cuotas-vencidas/{dniCliente}": {
    /** Auto generated using Swagger Inspector */
    get: {
      parameters: {
        path: {
          dniCliente: string;
        };
      };
      responses: {
        /** Auto generated using Swagger Inspector */
        200: {
          content: {
            "application/json; charset=utf-8":
              | components["schemas"]["CuotasVencidas"]
              | components["schemas"]["Error"];
          };
        };
        /** Auto generated using Swagger Inspector */
        400: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/productores/{numeroProductor}": {
    /** Auto generated using Swagger Inspector */
    get: {
      parameters: {
        path: {
          numeroProductor: string;
        };
      };
      responses: {
        /** Auto generated using Swagger Inspector */
        200: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Productor"];
          };
        };
        /** Auto generated using Swagger Inspector */
        400: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/coberturas/tipoVehiculo/{idTipoVehiculo}": {
    /** Auto generated using Swagger Inspector */
    get: {
      parameters: {
        path: {
          idTipoVehiculo: string;
        };
      };
      responses: {
        /** Auto generated using Swagger Inspector */
        200: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Coberturas"];
          };
        };
        /** Auto generated using Swagger Inspector */
        400: {
          content: {
            "application/json; charset=utf-8": components["schemas"]["Error"];
          };
        };
      };
    };
  };
  "/api/polizas": {
    /** Auto generated using Swagger Inspector */
    post: {
      responses: {
        /** Auto generated using Swagger Inspector */
        200: {
          content: {
            "application/json; charset=utf-8": { [key: string]: unknown };
          };
        };
        /** Auto generated using Swagger Inspector */
        400: {
          content: {
            "application/json; charset=utf-8": { [key: string]: unknown };
          };
        };
      };
      requestBody: {
        content: {
          "application/json": {
            cliente?: string;
            cobertura?: string;
            productor?: string;
            vehiculoAsegurado?: string;
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Cliente: {
      _id: string;
      fechaNacimiento: string;
      estadoCivil: string;
      nombre: string;
      apellido: string;
      dni: string;
      email: string;
      __v: number;
    };
    Error: {
      msg: string;
    };
    Cobertura: {
      _id?: string;
      codigoCobertura?: string;
      precio?: string;
      vehiculos?: string[];
      daños?: {
        _id?: string;
        nombre?: string;
        porcentaje?: string;
        descripcion?: string;
        __v?: number;
      }[];
      __v?: number;
    };
    Coberturas: components["schemas"]["Cobertura"][];
    VehiculoAsegurado: {
      patente?: string;
      color?: string;
      fotos?: string[];
      tipoVehiculo?: string;
      _id?: string;
      __v?: number;
    };
    Productor: {
      _id?: string;
      numeroProductor?: number;
      sucursal?: {
        _id?: string;
        numero?: number;
        direccion?: string;
        localidad?: {
          nombre?: string;
          provincia?: string;
          CP?: string;
          _id?: string;
        };
        __v?: number;
      };
      nombre?: string;
      apellido?: string;
      dni?: string;
      email?: string;
      __v?: number;
    };
    Cuota: {
      numero?: number;
      fecha?: string;
      importe?: string;
      estado?: string;
      _id?: string;
    };
    Polizas: {
      _id?: string;
      numeroPoliza?: number;
      fechaInicio?: string;
      fechaFin?: string;
      productor?: components["schemas"]["Productor"];
      cliente?: string;
      cobertura?: components["schemas"]["Cobertura"];
      vehiculoAsegurado?: {
        _id?: string;
        patente?: string;
        color?: string;
        fotos?: string[];
        __v?: number;
        tipoVehiculo?: {
          _id?: string;
          marca?: string;
          modelo?: string;
          version?: string;
          año?: string;
          __v?: number;
        };
        cuotas?: components["schemas"]["Cuota"][];
      };
    }[];
    CuotasVencidas: {
      msg?: string;
      cuotasVencidas?: components["schemas"]["Cuota"][];
    };
  };
}

export interface operations {}

export interface external {}
