export interface Cliente {
    _id:             string;
    fechaNacimiento: string;
    estadoCivil:     string;
    nombre:          string;
    apellido:        string;
    dni:             string;
    email:           string;
    __v:             number;
}

// Generated by https://quicktype.io

export interface Polizas {
    _id:               string;
    numeroPoliza:      number;
    fechaInicio:       string;
    fechaFin:          string;
    productor:         Productor;
    cliente:           string;
    cobertura:         Cobertura;
    vehiculoAsegurado: VehiculoAsegurado;
    cuotas:            Cuota[];
    __v:               number;
}

// Generated by https://quicktype.io

export interface Coberturas {
    _id:             string;
    codigoCobertura: string;
    precio:          string;
    vehiculos:       string[];
    daños:           Daño[];
    __v:             number;
}

interface Cobertura {
    _id:             string;
    codigoCobertura: string;
    precio:          string;
    vehiculos:       string[];
    daños:           Daño[];
    __v:             number;
}

interface Daño {
    _id:         string;
    nombre:      string;
    porcentaje:  string;
    descripcion: string;
    __v:         number;
}

interface Cuota {
    numero:  number;
    fecha:   string;
    importe: string;
    estado:  string;
    _id:     string;
}

interface Productor {
    _id:             string;
    numeroProductor: number;
    sucursal:        Sucursal;
    nombre:          string;
    apellido:        string;
    dni:             string;
    email:           string;
    __v:             number;
}

interface Sucursal {
    _id:       string;
    numero:    number;
    direccion: string;
    localidad: Localidad;
    __v:       number;
}

interface Localidad {
    nombre:    string;
    provincia: string;
    CP:        string;
    _id:       string;
}

interface VehiculoAsegurado {
    _id:          string;
    patente:      string;
    color:        string;
    fotos:        string[];
    tipoVehiculo: TipoVehiculo;
    __v:          number;
}

interface TipoVehiculo {
    _id:     string;
    marca:   string;
    modelo:  string;
    año:     string;
    version: string;
    __v:     number;
}